const shishamoSongs = [
  // 卒業制作
  { title: "宿題が終わらない", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  { title: "お菓子作り", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  { title: "君に告白した理由", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  { title: "夢のはなし", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  { title: "絆創膏", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  { title: "熱さまシート", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  { title: "冬の唄", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  { title: "第3ボタン", album: "卒業制作", artwork: "img/sotsugyoseisaku.jpg" },
  // SHISHAMO 1
  { title: "僕に彼女ができたんだ", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "行きたくない", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "あの子のバラード", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "こんな僕そんな君", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "休日", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "がたんごとん", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "深夜のラジオ", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "バンドマン", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "サブギターの歌", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "君との事", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  { title: "恋する", album: "SHISHAMO 1", artwork: "img/shishamo_1.jpg" },
  // SHISHAMO 2
  { title: "僕、実は", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "きみと話せないのは", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "彼女の日曜日", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "ともだち", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "君と夏フェス", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "量産型彼氏", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "恋愛休暇", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "昼夜逆転", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "デートプラン", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "花", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  { title: "さよならの季節", album: "SHISHAMO 2", artwork: "img/shishamo_2.jpg" },
  // SHISHAMO 3
  { title: "ごめんね、恋心", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "中庭の少女たち", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "生きるガール", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "笑顔のとなり", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "手のひら宇宙", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "推定移動距離", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "女ごころ", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "熱帯夜", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "旅がえり", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "君とゲレンデ", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  { title: "みんなのうた", album: "SHISHAMO 3", artwork: "img/shishamo_3.jpg" },
  // SHISHAMO 4
  { title: "好き好き！", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "すれちがいのデート", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "恋に落ちる音が聞こえたら", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "終わり", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "恋", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "音楽室は秘密基地", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "きっとあの漫画のせい", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "メトロ", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "夏の恋人", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "魔法のように", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  { title: "明日も", album: "SHISHAMO 4", artwork: "img/shishamo_4.jpg" },
  // SHISHAMO 5
  { title: "ねぇ、", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "ドキドキ", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "笑顔のおまじない", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "あなたと私の間柄", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "夢で逢う", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "あの娘の城", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "BYE BYE", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "同窓会", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "ほら、笑ってる", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "サボテン", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "ロマンチックに恋して", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "水色の日々", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  { title: "私の夜明け", album: "SHISHAMO 5", artwork: "img/shishamo_5.jpg" },
  // SHISHAMO 6
  { title: "天使みたい", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "ひっちゃかめっちゃか", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "君の大事にしてるもの", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "二酸化炭素", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "忘れてやるもんか", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "ハネノバシ", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "今だけは", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "真夜中、リビング、電気を消して。", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "フェイバリットボーイ", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "キスをちょうだい", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "またね", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "君の隣にいたいから", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  { title: "曇り夜空は雨の予報", album: "SHISHAMO 6", artwork: "img/shishamo_6.jpg" },
  // SHISHAMO 7
  { title: "中毒", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "人間", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "警報", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "明日はない", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "君の目も鼻も口も顎も眉も寝ても覚めても超素敵!!!", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "かわいい", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "明日の夜は何が食べたい？", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "ドライブ", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "はなればなれでも", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "壊したんだ", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "ごめんね", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "通り雨", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  { title: "夢で逢えても", album: "SHISHAMO 7", artwork: "img/shishamo_7.jpg" },
  // SHISHAMO 9
  { title: "最高速度", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "夏恋注意報", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "私のままで", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "会えないのに", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "犬ころ", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "ハリボテ", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "わたしの宇宙", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "きらきら", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "なんとなく。", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "春に迷い込んで", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "溺れてく", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "ハッピーエンド", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" },
  { title: "恋じゃなかったら", album: "SHISHAMO 9", artwork: "img/shishamo_9.jpg" }
];
